### PR TITLE
path sep

### PR DESCRIPTION
**Pull request by liyangmsn**

### CODE REVIEW

**Comment by smt116** [comment]
Why do we need this change?

**Comment by liyangmsn** [comment]
> Why do we need this change?

Ensure the consistency of multi-platform paths

**Comment by smt116** [comment]
I don't think it will. Paths on Windows use `\` and not `/`. After merging this PR, the extension would build the platform-aware path using `path.join` function, split it by `sep` (btw. there is no such configuration option in the extension API), and merge it again using UNIX-like separator. It will break builds on Windows.

**Comment by smt116** [comment]
Could you provide a reproducible example?

**Comment by liyangmsn** [comment]
> 
You're right
The path is determined at compile time.
But the runtime will make errors due to different platforms.

Because  `\\` cant't run on UNIX-like and `/` can run on window

so we need this change

**Comment by smt116** [comment]
It still won't work. When you will build a package with this PR for Linux as the target, and run it on Windows, it will use `/` as separator instead of `\`. In fact, you need to build separate packages for each target platform (see https://www.electron.build/multi-platform-build.html).

**Comment by liyangmsn** [comment]
> 

ok thanks

**Pull request closed without merging**
